version: "3.9"
services:
  api:
    build: .
    container_name: studentsathi-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks: [sathi]

  mongo:
    image: mongo:7
    container_name: studentsathi-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks: [sathi]

volumes:
  mongo_data:

networks:
  sathi:
    driver: bridge
